'use strict';

// Strip AI co-authorship and "generated by AI" trailers from a commit message,
// while keeping legitimate human co-authors. The project rule forbids AI
// attribution in commits; human contributor co-authorship stays untouched.
//
// Detection keys off vendor/assistant names only. It deliberately does NOT key
// off github noreply emails, because human contributors use those too and their
// co-authorship must be preserved.

const AI_SIGNATURE_PATTERNS = [
  'claude', 'anthropic', 'copilot', 'gemini', String.raw`google[-\s]?labs`, 'chatgpt', 'openai',
  String.raw`\bgpt-?\d?\b`, String.raw`\bcursor\b`, 'codeium', 'windsurf', String.raw`\bdevin\b`, 'tabnine',
  String.raw`amazon\s+q`, String.raw`\bcody\b`,
];
const AI_SIGNATURE = new RegExp(`(${AI_SIGNATURE_PATTERNS.join('|')})`, 'i');

// Full lines that are AI attribution regardless of trailer key. A leading run
// of non-word characters (a bullet or the robot emoji) is skipped with \W*, so
// this source needs no literal emoji. The line must carry a concrete AI
// signature (the shared vendor list) or the standalone word "AI": a generic
// token like "code" is not evidence, so "Generated by code" stays untouched.
const AI_GENERATED_LEAD = /^\W*generated\s+(with|by)\b/i;
const AI_WORD = /\bai\b/i;
const AI_ASSIST_TRAILER = /^\s*(co-authored-by|assisted-by|co-developed-with|generated-by|authored-by)\s*:/i;

function lineIsAiTrailer(line) {
  if (AI_GENERATED_LEAD.test(line) && (AI_SIGNATURE.test(line) || AI_WORD.test(line))) return true;
  if (AI_ASSIST_TRAILER.test(line) && AI_SIGNATURE.test(line)) return true;
  return false;
}

// Returns { message, removed } where removed is the list of stripped lines.
// Only AI attribution is removed; human co-authors and the rest of the message
// are preserved. Trailing blank lines left behind are collapsed.
function stripAiCoauthorship(message) {
  const text = String(message === null || message === undefined ? '' : message);
  const lines = text.split('\n');
  const removed = [];
  const kept = [];

  for (const line of lines) {
    if (lineIsAiTrailer(line)) {
      removed.push(line);
    } else {
      kept.push(line);
    }
  }

  if (removed.length === 0) {
    return { message: text, removed };
  }

  while (kept.length > 0 && kept.at(-1).trim() === '') {
    kept.pop();
  }

  const rebuilt = kept.join('\n');
  const message2 = text.endsWith('\n') ? `${rebuilt}\n` : rebuilt;
  return { message: message2, removed };
}

module.exports = { stripAiCoauthorship, lineIsAiTrailer };
